Read KVP values in binary mode
Azure/WALinuxAgent pull request #2084
Opened 2020-11-21 03:59 UTC by longlimsft

The KVP data is stored in binary format. The agent should read them in binary
mode. This fixes an issue with python3 incorrectly reading values from KVP.

## Description

Issue # 

---

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and Travis.CI is passing.

### Quality of Code and Contribution Guidelines
- [ ] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

2020-11-25 22:46 UTC, pgombar reviewed
Thank you for the fix. Could you please add a unit test for the changes? We need to support both Python2 and Python3 at the same time and make sure this is not a breaking change.

2020-11-25 22:46 UTC, pgombar commented on azurelinuxagent/common/rdma.py
> +                if key_0 :
nit: please remove extra whitespace

2020-11-25 22:46 UTC, pgombar commented on azurelinuxagent/common/rdma.py
> +                if value_0 :
nit: please remove extra whitespace

2020-12-02 02:35 UTC, longlimsft commented
@pgombar, this feature can only be tested in a HPC VM that reports ND version or SRIOV IB information over KVP. We have tested on both Python2 and Python3.

When a VM is deployed to a non-HPC size, this code path is not exercised.

2020-12-11 00:44 UTC, pgombar commented
> @pgombar, this feature can only be tested in a HPC VM that reports ND version or SRIOV IB information over KVP. We have tested on both Python2 and Python3.
> 
> When a VM is deployed to a non-HPC size, this code path is not exercised.

Thanks for confirming.

2020-12-11 01:07 UTC, pgombar commented
Running end-to-end automation: https://tuxgold.corp.microsoft.com/job/AzLinux/job/DungeonCrawler/view/WALinuxAgent/job/DungeonCrawler.pagombar2/15/

2020-12-11 03:05 UTC, pgombar submitted a review, later dismissed
End-to-end automation ok (no new issues).

2020-12-14 17:37 UTC, kevinclark19a submitted a review, later dismissed

2020-12-14 18:13 UTC, narrieta submitted a review, later dismissed

2020-12-14 18:14 UTC, larohra requested changes

2020-12-14 18:14 UTC, larohra commented on azurelinuxagent/common/rdma.py
> +        f = open(driver_info_source, "rb")  # pylint: disable=C0103
NIT: Please fix the pylint warning 
`# pylint: disable=C0103`

2020-12-14 18:14 UTC, larohra commented on azurelinuxagent/common/rdma.py
>                      f.close()
This comment does not directly related to your changes, but could you please move the file closing to either a `finally` clause or move the file operations to under a `with` clause. This is to ensure that the file always gets closed even if there is some exception thrown while processing the data. 

Sample usage: https://cmdlinetips.com/2016/01/opening-a-file-in-python-using-with-statement/

Thanks!

2020-12-14 19:33 UTC, larohra approved these changes

2020-12-14 19:34 UTC, narrieta approved these changes

2020-12-14 19:37 UTC, pgombar commented
Running automation again: https://tuxgold.corp.microsoft.com/job/AzLinux/job/DungeonCrawler/view/WALinuxAgent/job/DungeonCrawler.pagombar2/16/

2020-12-14 20:52 UTC, merged