Adding verbiage for supported method of installation of waagent.
Azure/WALinuxAgent pull request #3011
Opened 2024-01-06 22:02 UTC by mabicca

Adding correct verbiage for installation to make sure we mention that the supported method of installation is through the official distribution's repositories.

## Description

Issue # 

---

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made

### Quality of Code and Contribution Guidelines
- [ ] I have read the [contribution guidelines](https://github.com/Azure/WALinuxAgent/blob/master/.github/CONTRIBUTING.md).

2024-01-07 23:35 UTC, maddieford approved these changes

2024-01-08 15:48 UTC, maddieford requested changes
Please also update the PR to merge into develop instead of master

2024-02-16 17:30 UTC, mabicca commented
@narrieta do you think we could get this finally updated? We have to clarify this as we keep seeing customers and other engineers suggesting to install from source. Unless we fully support it, it should say in our docs clearly that it is not. Please, let me know. We can work to rephrase this.

2024-02-16 17:45 UTC, narrieta commented
@mabicca it's already updated in the latest release; it''l get merged to master once the release is complete. closing this PR, thanks for opening it
```

Installation
Installing via your distribution's package repository is the only method that is supported.

You can install from source for more advanced options, such as installing to a custom location or creating custom images. Installing from source, though, may override customizations done to the Agent by your distribution, and is meant only for advanced users. We provide very limited support for this method.

To install from source, you can use setuptools:

    sudo python setup.py install --register-service
For Python 3, use:

    sudo python3 setup.py install --register-service
You can view more installation options by running:

    sudo python setup.py install --help
The agent's log file is kept at /var/log/waagent.log.

Lastly, you can also customize your own RPM or DEB packages using the configuration samples provided in the deb and rpm sections below. This method is also meant for advanced users and we provide very limited support for it.
```

2024-02-16 17:45 UTC, closed without merging